
- name: Install pip
  yum:
    name: python-pip
    state: present

- name: Install docker-py with pip
  pip:
    name:
      - docker
      - docker-compose

- name: Run container
  docker_container:
    name: wartest_container
    image: "{{ image }}"
    state: started
    published_ports:
      - "8081:8080"




